[package]
name = "MoveIntegers"
version = "1.0.0"
authors = ["0xAnto"]

[addresses]
move_int = "0x22fd2f1104e76c947e132056e67f1a30f45833093e99fe75b23cb9e20a72e7ee"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
