[package]
name = "MoveIntegers"
version = "1.0.0"
authors = ["0xAnto"]

[addresses]
move_int = "0xcff27db92178da13d6543c9036552fcee0f4c7a2cca464e58bab1f40db2296e7"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "l1-migration-move2"
subdir = "aptos-move/framework/aptos-framework"
